apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  bruno.boujenah-prestataire@laposte.fr
    privateKeySecretRef:
      name: ingress-cert
    solvers:
      - http01:
          ingress:
            class: istio