# redirection d'un user ver la v2 de reviews
# restriction --> https://istio.io/latest/docs/ops/deployment/requirements/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: poc-bbo
spec:
  hosts:
    - reviews
  http:
    - match:
        - headers:
            end-user:
              exact: bbo
      route:
        - destination:
            host: reviews
            subset: v2
    - route:
        - destination:
            host: reviews
            subset: v1